### PR TITLE
use Timeval32 for darwin and Timeval for the other bsd variants

### PR DESCRIPTION
**Pull request by wardn**

### CODE REVIEW

**Comment by kenshaw** [comment]
Can you explain the necessity for this change?

**Comment by wardn** [comment]
Timeval32 only exists in the darwin and solaris types so it fails to build on on the other bsd variants.

**Comment by kenshaw** [comment]
Sorry, my mistake for not noticing that. Why not just change to Timeval on all BSD variants? I'd prefer not duplicating this code everywhere.

**Comment by wardn** [comment]
Didn't want to fix what wasn't broken on darwin, but I agree that it's less maintenance.  Updates applied.

**Comment by kenshaw** [comment]
I've tested this; simply changing it from the Timeval32 to Timeval type causes a "unexpected EOF" error on the binary.Read call on darwin. I'm assuming you're using this / testing this on an actual *BSD host? I don't have BSD installed in a VM. I'm reading the docs / types for openbsd, and its probably not possible to use the same type. I would suggest that we define a separate "Timeval" type in a separate file that has the correct versions for the BSD variants. I'll make a point of putting FreeBSD + OpenBSD into a VM for testing.

**Comment by kenshaw** [comment]
Appreciate the changes, can you please rename the files to `types_<OS>.go` -- ie, `types_bsd.go`? This will make it consistent with file naming conventions for build tags.

**Comment by wardn** [comment]
The types_bsd.go convention would cause problems since darwin is included in the bsd definition.  This latest push should be the most idiomatic per the https://github.com/golang/go/tree/master/src/syscall file structure.

**Comment by kenshaw** [comment]
I believe you can do this:
```
timeval_darwin.go  with // +build darwin
timeval_bsd.go with // +build !darwin
```

**Comment by kenshaw** [comment]
I appreciate the work you did here, btw! I found other issues in general, but fixed it so that it works properly on freebsd + openbsd. Since the netbsd port isn't correctly working, I haven't tried it there.

**Pull request closed without merging**
